default:
    suites:
        ui_pimcore_filter:
            contexts:
                - coreshop.behat.context.hook.pimcore_setup
                - coreshop.behat.context.hook.coreshop_setup

                - CoreShop\Bundle\TestBundle\Context\Hook\DoctrineORMContext
                - coreshop.behat.context.hook.pimcore_dao

                - CoreShop\Bundle\TestBundle\Context\Transform\SharedStorageContext

                - coreshop.behat.context.ui_pimcore.login
                - coreshop.behat.context.ui_pimcore.menu
            filters:
                tags: "@ui_pimcore&&@filter"
