default:
    suites:
        domain_currency:
            contexts:
                - coreshop.behat.context.hook.pimcore_setup
                - coreshop.behat.context.hook.coreshop_setup

                - CoreShop\Bundle\TestBundle\Context\Hook\DoctrineORMContext
                - coreshop.behat.context.hook.pimcore_dao

                - CoreShop\Bundle\TestBundle\Context\Transform\SharedStorageContext
                - coreshop.behat.context.transform.currency
                - coreshop.behat.context.transform.store
                - coreshop.behat.context.transform.country

                - coreshop.behat.context.setup.store
                - coreshop.behat.context.setup.country
                - coreshop.behat.context.setup.currency
                - coreshop.behat.context.setup.exchange_rate

                - coreshop.behat.context.domain.currency
                - coreshop.behat.context.domain.exchange_rate
            filters:
                tags: "@domain&&@currency"
