default:
    suites:
        domain_filter:
            contexts:
                - coreshop.behat.context.hook.pimcore_setup
                - coreshop.behat.context.hook.coreshop_setup

                - CoreShop\Bundle\TestBundle\Context\Hook\DoctrineORMContext
                - coreshop.behat.context.hook.pimcore_dao

                - CoreShop\Bundle\TestBundle\Context\Transform\SharedStorageContext
                - CoreShop\Bundle\TestBundle\Context\Transform\ClassContext
                - coreshop.behat.context.transform.product
                - coreshop.behat.context.transform.category
                - coreshop.behat.context.transform.manufacturer
                - coreshop.behat.context.transform.store
                - coreshop.behat.context.transform.index
                - coreshop.behat.context.transform.filter

                - coreshop.behat.context.setup.index
                - coreshop.behat.context.setup.filter
                - coreshop.behat.context.setup.product
                - coreshop.behat.context.setup.category
                - coreshop.behat.context.setup.manufacturer
                - coreshop.behat.context.setup.store
                - CoreShop\Bundle\TestBundle\Context\Setup\ClassContext

                - coreshop.behat.context.domain.filter
            filters:
                tags: "@domain&&@filter"
