default:
    suites:
        domain_menu:
            contexts:
                - coreshop.behat.context.hook.pimcore_setup
                - coreshop.behat.context.hook.coreshop_setup

                - CoreShop\Bundle\TestBundle\Context\Hook\DoctrineORMContext
                - coreshop.behat.context.hook.pimcore_dao

                - coreshop.behat.context.domain.menu
            filters:
                tags: "@domain&&@menu"
