default:
    suites:
        domain_seo:
            contexts:
                - coreshop.behat.context.hook.pimcore_setup
                - coreshop.behat.context.hook.coreshop_setup

                - CoreShop\Bundle\TestBundle\Context\Hook\DoctrineORMContext
                - coreshop.behat.context.hook.pimcore_dao

                - CoreShop\Bundle\TestBundle\Context\Transform\SharedStorageContext
                - coreshop.behat.context.transform.product
                - coreshop.behat.context.transform.category

                - coreshop.behat.context.setup.product
                - coreshop.behat.context.setup.category

                - coreshop.behat.context.domain.seo
            filters:
                tags: "@domain&&@seo"
