default:
    suites:
        ui_customer_profile:
            contexts:
                - coreshop.behat.context.hook.pimcore_setup
                - coreshop.behat.context.hook.coreshop_setup

                - CoreShop\Bundle\TestBundle\Context\Hook\DoctrineORMContext
                - coreshop.behat.context.hook.pimcore_dao

                - CoreShop\Bundle\TestBundle\Context\Transform\SharedStorageContext
                - coreshop.behat.context.transform.tax_rate
                - coreshop.behat.context.transform.tax_rule_group
                - coreshop.behat.context.transform.store
                - coreshop.behat.context.transform.product
                - coreshop.behat.context.transform.country
                - coreshop.behat.context.transform.customer

                - coreshop.behat.context.setup.store
                - coreshop.behat.context.setup.frontend_security
                - coreshop.behat.context.setup.customer

                - coreshop.behat.context.ui.customer_profile
            filters:
                tags: "@ui&&@customer_profile"
