services:
    _defaults:
        public: true

    coreshop.behat.context.hook.doctrine_orm: '@CoreShop\Bundle\TestBundle\Context\Hook\DoctrineORMContext'

    coreshop.behat.context.hook.pimcore_dao:
        class: CoreShop\Behat\Context\Hook\PimcoreDaoContext
        arguments:
            - '@kernel'
            - '@coreshop.repository.order'
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.hook.pimcore_setup:
        class: CoreShop\Behat\Context\Hook\PimcoreSetupContext
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.hook.coreshop_setup:
        class: CoreShop\Behat\Context\Hook\CoreShopSetupContext
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@CoreShop\Bundle\CoreBundle\Test\Service\NotificationRuleListener'
            - '@event_dispatcher'
        tags:
            - { name: fob.context_service }
