services:
    _defaults:
        public: true

    coreshop.behat.context.ui.homepage:
        class: CoreShop\Behat\Context\Ui\Frontend\HomepageContext
        arguments:
            - '@CoreShop\Behat\Page\Frontend\HomePageInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.login:
        class: CoreShop\Behat\Context\Ui\Frontend\LoginContext
        arguments:
            - '@CoreShop\Behat\Page\Frontend\HomePageInterface'
            - '@CoreShop\Behat\Page\Frontend\Account\LoginPageInterface'
            - '@CoreShop\Behat\Page\Frontend\Account\RequestPasswordResetPageInterface'
            - '@CoreShop\Bundle\TestBundle\Service\Resolver\CurrentPageResolverInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.register:
        class: CoreShop\Behat\Context\Ui\Frontend\RegistrationContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@CoreShop\Behat\Page\Frontend\HomePageInterface'
            - '@CoreShop\Behat\Page\Frontend\Account\LoginPageInterface'
            - '@CoreShop\Behat\Page\Frontend\Account\RegisterPageInterface'
            - '@CoreShop\Behat\Element\Frontend\Account\RegisterElementInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.customer_profile:
        class: CoreShop\Behat\Context\Ui\Frontend\CustomerProfileContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@CoreShop\Behat\Page\Frontend\Account\ChangePasswordPageInterface'
            - '@CoreShop\Behat\Page\Frontend\Account\ProfilePageInterface'
            - '@CoreShop\Behat\Page\Frontend\Account\ChangeProfilePageInterface'
            - '@CoreShop\Bundle\TestBundle\Service\NotificationCheckerInterface'
            - '@CoreShop\Behat\Page\Frontend\Account\ChangeAddressPageInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.product:
        class: CoreShop\Behat\Context\Ui\Frontend\ProductContext
        arguments:
            - '@behat.mink.default_session'
            - '@CoreShop\Behat\Page\Frontend\ProductPageInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.cart:
        class: CoreShop\Behat\Context\Ui\Frontend\CartContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@CoreShop\Bundle\TestBundle\Service\NotificationCheckerInterface'
            - '@CoreShop\Behat\Page\Frontend\CartPageInterface'
            - '@CoreShop\Behat\Page\Frontend\CartCreatePageInterface'
            - '@CoreShop\Behat\Page\Frontend\CartsListPageInterface'
            - '@CoreShop\Behat\Page\Frontend\ProductPageInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.wishlist:
        class: CoreShop\Behat\Context\Ui\Frontend\WishlistContext
        arguments:
            - '@coreshop.behat.shared_storage'
            - '@CoreShop\Behat\Page\Frontend\WishlistPageInterface'
            - '@CoreShop\Behat\Page\Frontend\ProductPageInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.user:
        class: CoreShop\Behat\Context\Ui\Frontend\UserContext
        arguments:
            - '@CoreShop\Behat\Page\Frontend\HomePageInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.store:
        class: CoreShop\Behat\Context\Ui\Frontend\StoreContext
        arguments:
            - '@CoreShop\Behat\Service\StoreContextSetterInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.currency:
        class: CoreShop\Behat\Context\Ui\Frontend\CurrencyContext
        arguments:
            - '@CoreShop\Behat\Page\Frontend\HomePageInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.checkout:
        class: CoreShop\Behat\Context\Ui\Frontend\CheckoutContext
        arguments:
            - '@CoreShop\Behat\Page\Frontend\Checkout\CustomerPageInterface'
            - '@CoreShop\Behat\Page\Frontend\Checkout\AddressPageInterface'
            - '@CoreShop\Behat\Page\Frontend\Checkout\ShippingPageInterface'
            - '@CoreShop\Behat\Page\Frontend\Checkout\PaymentPageInterface'
            - '@CoreShop\Behat\Page\Frontend\Checkout\SummaryPageInterface'
            - '@CoreShop\Behat\Page\Frontend\Checkout\ThankYouPageInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.domain.payment:
        class: CoreShop\Behat\Context\Ui\Domain\PaymentController
        arguments:
            - '@payum'
            - '@router'
            - '@CoreShop\Bundle\WorkflowBundle\StateManager\WorkflowStateInfoManagerInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.category:
        class: CoreShop\Behat\Context\Ui\Frontend\CategoryContext
        arguments:
           - '@CoreShop\Behat\Page\Frontend\HomePageInterface'
           - '@CoreShop\Behat\Page\Frontend\CategoryPageInterface'
        tags:
            - { name: fob.context_service }

    coreshop.behat.context.ui.filter:
        class: CoreShop\Behat\Context\Ui\Frontend\FilterContext
        arguments:
            - '@CoreShop\Behat\Page\Frontend\CategoryPageInterface'
        tags:
            - { name: fob.context_service }
