imports:
    - { resource: services/contexts.yml }
    - { resource: services/pages.yml }
    - { resource: services/pages_pimcore.yml }
    - { resource: services/elements.yml }
    - { resource: services/elements_pimcore.yml }

payum:
    gateways:
        offline:
            factory: concurrency

core_shop_address:
    autoconfigure_with_attributes: true

core_shop_resource:
    mapping:
        paths:
            - '%kernel.project_dir%/src/CoreShop/Behat/Model'

services:
    _defaults:
        public: true

    coreshop.behat.shared_storage: '@CoreShop\Bundle\TestBundle\Service\SharedStorageInterface'
    coreshop.behat.class_storage: '@CoreShop\Bundle\TestBundle\Service\ClassStorageInterface'

    CoreShop\Behat\Service\Index\RelationalIndexExtension:
        tags:
            - { name: coreshop.index.extension }

    CoreShop\Behat\Service\Index\IndexColumnExtension:
        tags:
            - { name: coreshop.index.extension }

    CoreShop\Behat\Service\CustomRelationalIndexInterpreter:
        tags:
            - { name: coreshop.index.interpreter, type: custom_relational }

    CoreShop\Behat\Service\StoreContextSetterInterface: '@CoreShop\Behat\Service\StoreContextSetter'
    CoreShop\Behat\Service\StoreContextSetter:
        arguments:
            - '@CoreShop\Bundle\TestBundle\Service\CookieSetterInterface'

    payum.concurrency_gateway_factory:
        class: Payum\Bundle\PayumBundle\Builder\GatewayFactoryBuilder
        arguments: [ CoreShop\Behat\Service\Payum\Concurrency\ConcurrencyGatewayFactory ]
        tags:
            - { name: payum.gateway_factory_builder, factory: concurrency }

    CoreShop\Behat\Service\SampleCountryContext:
        autoconfigure: true