twig:
    form_themes:
        - '@CoreShopFrontend/Form/fields.html.twig'

# TODO SET CORRECT THE PATH #
webpack_encore:
    output_path: '%kernel.project_dir%/src/CoreShop/Bundle/FrontendBundle/Resources/public/build'
    script_attributes:
        defer: true