coreshop_payment_after:
    path: /cs/after-pay
    methods: [GET, POST]
    defaults:
        _controller: CoreShop\Bundle\PayumBundle\Controller\PaymentController::afterCaptureAction

coreshop_get_cart_items:
    path: /coreshop_get_cart_items
    methods: [GET]
    defaults:
        _controller: CoreShop\Bundle\FrontendBundle\Controller\CartController::widgetAction
