name: Monorepo split
on:
    push:
        branches:
            - next
            - 2.0
            - 2.1
            - 2.2
            - 3.0
            - 3.1
            - 4.0
            - 4.1
        paths:
            - 'src/CoreShop/Bundle/**'
            - 'src/CoreShop/Component/**'
    release:
        types: [ published ]

jobs:
    gitsplit:
        runs-on: ubuntu-latest
        steps:
            -
                name: Full checkout
                run: git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY /home/runner/work/CoreShop/CoreShop && cd /home/runner/work/CoreShop/CoreShop && git checkout $GITHUB_SHA
            -
                name: Copy gitsplit config
                run: mkdir /home/runner/work/CoreShop/CoreShopSplit && cd /home/runner/work/CoreShop/CoreShopSplit && cp /home/runner/work/CoreShop/CoreShop/.gitsplit.yml /home/runner/work/CoreShop/CoreShopSplit/.gitsplit.yml
            -
                name: Gitsplit Cache
                id: gitsplit-cache
                uses: actions/cache@v4
                with:
                    path: cache
                    key: gitsplit-cache
            -
                name: Split repositories
                uses: docker://jderusse/gitsplit:latest
                with:
                    args: gitsplit
                env:
                    GH_TOKEN: ${{ secrets.GITSPLIT_TOKEN }}
